;;; p3-performance-regression-test.el --- Responsiveness regression tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'p3-commands)
(require 'p3-platform)
(require 'p3-project)

(ert-deftest p3-performance-routed-remote-file-keeps-project-discovery-unresolved ()
  (let ((project-current-calls 0))
    (cl-letf (((symbol-function 'file-remote-p)
               (lambda (_file &optional _identification) t))
              ((symbol-function 'p3/project-route-file)
               (lambda (_file) nil))
              ((symbol-function 'project-current)
               (lambda (&optional _maybe-prompt _directory)
                 (setq project-current-calls (1+ project-current-calls))
                 'remote-project))
              ((symbol-function 'project-root)
               (lambda (_project) "/ssh:example:/srv/project/")))
      (p3/project-with-file-routing
       (lambda (&rest _args)
         (should
          (equal (p3/project-root)
                 "/ssh:example:/srv/project/")))
       "/ssh:example:/srv/project/file.R")
      (should (= project-current-calls 1)))))

(ert-deftest p3-performance-windows-refresh-clears-stale-tool-state ()
  (let* ((old-rtools "C:/rtools45")
         (old-bin "C:/rtools45/usr/bin/")
         (old-r "C:/Program Files/R/R-4.5.1/bin/Rterm.exe")
         (path-separator ";")
         (rtools-path old-rtools)
         (linuxy-environment-path old-bin)
         (mingw64-path "C:/rtools45/mingw64/bin/")
         (p3/windows-hunspell-program "C:/rtools45/usr/bin/hunspell.exe")
         (p3/windows-hunspell-dictionary-directory "C:/rtools45/usr/share/hunspell")
         (p3/windows-rtools-selection-cache (list nil old-rtools))
         (p3/windows-r-program-selection-cache (list nil old-r))
         (p3/windows-rtools-override nil)
         (p3/windows-r-program-override nil)
         (exec-path (list old-bin "C:/Emacs/bin/"))
         (shell-file-name "C:/rtools45/usr/bin/bash.exe")
         (explicit-shell-file-name "C:/rtools45/usr/bin/bash.exe")
         (old-path (getenv "PATH"))
         (old-shell (getenv "SHELL"))
         (inferior-was-bound (boundp 'inferior-R-program-name))
         (old-inferior (and inferior-was-bound
                            (default-value 'inferior-R-program-name))))
    (unwind-protect
        (progn
          (setenv "PATH" "C:/rtools45/usr/bin;C:/Windows/System32")
          (setenv "SHELL" "C:/rtools45/usr/bin/bash.exe")
          (setq-default inferior-R-program-name old-r)
          (cl-letf (((symbol-function 'p3/windows-p) (lambda () t))
                    ((symbol-function 'p3/windows-latest-rtools) (lambda () nil))
                    ((symbol-function 'p3/windows-latest-r-program) (lambda () nil))
                    ((symbol-function 'display-warning) (lambda (&rest _args) nil)))
            (p3/windows-refresh-tool-discovery))
          (should-not rtools-path)
          (should-not linuxy-environment-path)
          (should-not mingw64-path)
          (should-not p3/windows-hunspell-program)
          (should-not p3/windows-hunspell-dictionary-directory)
          (should-not (member old-bin exec-path))
          (should-not (string-match-p
                       (regexp-quote "C:/rtools45/usr/bin")
                       (or (getenv "PATH") "")))
          (should-not (equal shell-file-name "C:/rtools45/usr/bin/bash.exe"))
          (should-not explicit-shell-file-name)
          (should-not (getenv "SHELL"))
          (should-not (default-value 'inferior-R-program-name)))
      (setenv "PATH" old-path)
      (setenv "SHELL" old-shell)
      (if inferior-was-bound
          (setq-default inferior-R-program-name old-inferior)
        (makunbound 'inferior-R-program-name)))))

(ert-deftest p3-performance-profile-file-visit-profiles-full-display-path ()
  (require 'profiler)
  (let* ((file (make-temp-file "p3-profile-file-visit-"))
         started
         stopped
         reported
         visited)
    (unwind-protect
        (cl-letf (((symbol-function 'get-file-buffer) (lambda (_file) nil))
                  ((symbol-function 'profiler-start)
                   (lambda (type) (setq started type)))
                  ((symbol-function 'profiler-stop)
                   (lambda () (setq stopped t)))
                  ((symbol-function 'profiler-report)
                   (lambda () (setq reported t)))
                  ((symbol-function 'find-file)
                   (lambda (path) (setq visited path))))
          (should (numberp (p3/profile-file-visit file)))
          (should (eq started 'cpu+mem))
          (should stopped)
          (should reported)
          (should (equal visited (expand-file-name file))))
      (delete-file file))))

(provide 'p3-performance-regression-test)

;;; p3-performance-regression-test.el ends here
