;;; p3-terminal-test.el --- Tests for p3-terminal -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(defconst p3-terminal-test--root
  (file-name-directory
   (directory-file-name
    (file-name-directory (or load-file-name buffer-file-name))))
  "Root of the Emacs configuration under test.")

(add-to-list 'load-path (expand-file-name "lisp" p3-terminal-test--root))

(require 'p3-core)
(require 'p3-terminal)

(ert-deftest p3-terminal-buffer-name-is-stable-and-root-specific ()
  (let ((first (p3/project-shell-buffer-name "/tmp/project-a/"))
        (again (p3/project-shell-buffer-name "/tmp/project-a/"))
        (second (p3/project-shell-buffer-name "/tmp/project-b/")))
    (should (equal first again))
    (should-not (equal first second))
    (should
     (string-match-p
      "\\`\\*shell:project-a:[[:xdigit:]]\\{6\\}\\*\\'" first))))

(ert-deftest p3-terminal-root-prefers-project-root ()
  (let ((default-directory "/tmp/fallback/"))
    (cl-letf (((symbol-function 'p3/project-root)
               (lambda () "/tmp/project/")))
      (should (equal (p3/project-shell-root) "/tmp/project/")))))

(ert-deftest p3-terminal-root-falls-back-to-local-default-directory ()
  (let ((default-directory "/tmp/fallback/"))
    (cl-letf (((symbol-function 'p3/project-root) (lambda () nil)))
      (should (equal (p3/project-shell-root) "/tmp/fallback/")))))

(ert-deftest p3-terminal-root-rejects-remote-fallback ()
  (let ((default-directory "/ssh:host:/tmp/project/"))
    (cl-letf (((symbol-function 'p3/project-root) (lambda () nil)))
      (should-error (p3/project-shell-root) :type 'user-error))))

(ert-deftest p3-terminal-primary-shell-is-reused-per-root ()
  (let ((p3/project-shell-buffers (make-hash-table :test #'equal))
        (created nil))
    (unwind-protect
        (cl-letf (((symbol-function 'p3/project-root)
                   (lambda () "/tmp/project/"))
                  ((symbol-function 'p3/project-shell--start)
                   (lambda (name _root)
                     (let ((buffer (get-buffer-create name)))
                       (push buffer created)
                       buffer))))
          (let ((first (p3/project-shell-buffer))
                (second (p3/project-shell-buffer)))
            (should (eq first second))
            (should (= (length created) 1))))
      (mapc (lambda (buffer)
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))
            created))))

(ert-deftest p3-terminal-primary-shell-is-root-specific ()
  (let ((p3/project-shell-buffers (make-hash-table :test #'equal))
        (root "/tmp/project-a/")
        created)
    (unwind-protect
        (cl-letf (((symbol-function 'p3/project-root) (lambda () root))
                  ((symbol-function 'p3/project-shell--start)
                   (lambda (name _root)
                     (let ((buffer (get-buffer-create name)))
                       (push buffer created)
                       buffer))))
          (let ((first (p3/project-shell-buffer)))
            (setq root "/tmp/project-b/")
            (let ((second (p3/project-shell-buffer)))
              (should-not (eq first second))
              (should (= (length created) 2)))))
      (mapc (lambda (buffer)
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))
            created))))

(ert-deftest p3-terminal-extra-session-does-not-replace-primary ()
  (let ((p3/project-shell-buffers (make-hash-table :test #'equal))
        created)
    (unwind-protect
        (cl-letf (((symbol-function 'p3/project-root)
                   (lambda () "/tmp/project/"))
                  ((symbol-function 'p3/project-shell--start)
                   (lambda (name _root)
                     (let ((buffer (get-buffer-create name)))
                       (push buffer created)
                       buffer))))
          (let ((primary (p3/project-shell-buffer))
                (extra (p3/project-shell-buffer t)))
            (should-not (eq primary extra))
            (should (eq primary (p3/project-shell-buffer)))
            (should (= (length created) 2))))
      (mapc (lambda (buffer)
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))
            created))))

(ert-deftest p3-terminal-stale-primary-is-replaced ()
  (let ((p3/project-shell-buffers (make-hash-table :test #'equal))
        created)
    (unwind-protect
        (cl-letf (((symbol-function 'p3/project-root)
                   (lambda () "/tmp/project/"))
                  ((symbol-function 'p3/project-shell--start)
                   (lambda (name _root)
                     (let ((buffer (get-buffer-create name)))
                       (push buffer created)
                       buffer))))
          (let ((first (p3/project-shell-buffer)))
            (kill-buffer first)
            (let ((replacement (p3/project-shell-buffer)))
              (should (buffer-live-p replacement))
              (should-not (eq first replacement)))))
      (mapc (lambda (buffer)
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))
            created))))

(ert-deftest p3-terminal-shell-starts-with-root-as-default-directory ()
  (let ((p3/project-shell-buffers (make-hash-table :test #'equal))
        captured-directory
        created)
    (unwind-protect
        (cl-letf (((symbol-function 'p3/project-root)
                   (lambda () "/tmp/project/"))
                  ((symbol-function 'p3/project-shell--start)
                   (lambda (name _root)
                     (setq captured-directory default-directory)
                     (let ((buffer (get-buffer-create name)))
                       (push buffer created)
                       buffer))))
          (p3/project-shell-buffer)
          (should (equal captured-directory "/tmp/project/")))
      (mapc (lambda (buffer)
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))
            created))))

(ert-deftest p3-terminal-command-map-exposes-session-workflow ()
  (dolist (binding '(("t" . p3/project-shell)
                     ("n" . p3/project-shell-new)
                     ("s" . p3/project-shell-switch)
                     ("o" . p3/project-shell-other-window)
                     ("r" . p3/project-shell-rename)
                     ("k" . p3/project-shell-kill)))
    (should (eq (keymap-lookup p3/project-shell-command-map (car binding))
                (cdr binding)))))

(provide 'p3-terminal-test)

;;; p3-terminal-test.el ends here
